CREATE SCHEMA dbex;

/*markdown
## Criando A tabela coluna
*/

CREATE TABLE IF NOT EXISTS dbex.cidades (
    id serial PRIMARY KEY,
    nome varchar(150) NOT NULL,
    estado char(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS dbex.cidades (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome varchar(150) NOT NULL,
    estado char(2) NOT NULL DEFAULT '--'
);

CREATE TABLE IF NOT EXISTS dbex.cidades (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(150) NOT NULL,
    estado char(2) NOT NULL
);

/*markdown
## Removendo a tabela cidades
*/

DROP TABLE dbex.cidades;

/*markdown
## Tamanho da String
*/

SELECT octet_length('IFRN'::varchar(8));

/*markdown
## CHAR é para marcar o prenchimento exato
*/

SELECT octet_length('IFRN'::char(8));

/*markdown
## Visualizando os dados da tabela Cidades
*/

SELECT FROM * dbex.cidades;

CREATE  TABLE IF NOT EXISTS dbex.localizalizacoes (
    id int GENERATED ALWAYS AS IDENTITY,
    id_cidade int NOT NULL,
    latitude float NOT NULL,
    longitude float NOT NULL,
    CONSTRAINT localizalizacoes_pk PRIMARY KEY(id),
    CONSTRAINT localizalizacoes_cidades_fk 
            FOREIGN KEY (id_cidade) REFERENCES dbex.cidades(id)

);

CREATE  TABLE IF NOT EXISTS dbex.localizalizacoes (
    id int GENERATED ALWAYS AS IDENTITY,
    id_cidade int NOT NULL;
    temp_min int NOT NULL;
    temp_max int NOT NULL;
    CONSTRAINT localizalizacoes_pk PRIMARY KEY(id),
    CONSTRAINT localizalizacoes_cidades_fk 
            FOREIGN KEY (id_cidade) REFERENCES dbex.cidades(id)

)